/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenparcial2;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class ADDTROPHIETO extends javax.swing.JFrame {

    /**
     * Creates new form ADDTROPHIETO
     */
    public ADDTROPHIETO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ACEPTAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TrophyGame = new javax.swing.JTextField();
        TrophyName = new javax.swing.JTextField();
        TrophyType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        REG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD TROPHIE TO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 530, -1));

        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });
        getContentPane().add(ACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel2.setText("NOMBRE DE USUARIO: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 150, -1));

        jLabel3.setText("Trophy Name:  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));
        getContentPane().add(TrophyGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, -1));

        TrophyName.setText(" ");
        getContentPane().add(TrophyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 150, -1));
        getContentPane().add(TrophyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 150, -1));

        jLabel4.setText("Trophy Type:  ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel5.setText("Trophy Game:  ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        REG.setText("REGRESAR");
        REG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGActionPerformed(evt);
            }
        });
        getContentPane().add(REG, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 504, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGActionPerformed
        menuPrincipal mP=new menuPrincipal();
        mP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_REGActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        try {
            String user=username.getText();
            String Trophygame=TrophyGame.getText();
            String Trophyname=TrophyName.getText();
            Trophy type=Trophy.valueOf(TrophyType.getText());
            
            PSNUsers.addTrophyTo(user, Trophygame, Trophyname, type);
            JOptionPane.showMessageDialog(null, "User agregado");
            menuPrincipal mP=new menuPrincipal();
            mP.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(ADDTROPHIETO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ACEPTARActionPerformed

    /**
     * @param args the command line arguments
     */   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton REG;
    private javax.swing.JTextField TrophyGame;
    private javax.swing.JTextField TrophyName;
    private javax.swing.JTextField TrophyType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
